name: Build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  release:
    types: [created]

jobs:
  build:
    name: Building on ${{matrix.os}} using ${{matrix.compiler}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
        compiler: [fsf, community]
    steps:
    - uses: actions/checkout@v2

    - name: Install toolchain
      uses: ada-actions/toolchain@ce2021
      with:
        distrib: ${{matrix.compiler}}
        target: native

    - name: Install Alire
      uses: alire-project/setup-alire@latest-devel

    - name: Build crates
      run: make
